### ISSUE TITLE
Http middleware appends url with path and query params to url

### ISSUE THREAD

**Issue by MarcMogdanz** [narando/nest-xray#140]
The http middleware uses a function called [`patchSegmentURL`](https://github.com/narando/nest-xray/blob/master/lib/environments/http/tracing.middleware.ts#L37) which appends path with query params to the url without the path (but with query params if there are any) which results in X-Ray traces like this: 

`http://widgets.narando.com/?url=https://example.com/foo/bar/articles?url=https://example.com/foo/bar/`

**Comment by apricote** [comment]
The [official docs](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html#api-segmentdocuments-http) include the following about the submitted url:

> `url` – The full URL of the request, compiled from the protocol, hostname, and path of the request.

So I will update the method to scrub the whole query string from the request.
