### ISSUE TITLE
Export the exceptions

### ISSUE THREAD

**Issue by charlie-harvey** [narando/nest-xray#152]
Exceptions are not exported. I can't use them in my code. The `/lib/exceptions/index.ts` exports them, but nothing references that `/lib/exceptions/index.ts` file.

Also, Errors are dumb in Typescript and you can't actually do `instanceof` on them.
https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work

```
export class TracingNotInitializedException extends Error {
    constructor(m: string) {
        super(
            `Tracing was used in a code path that is not wrapped in AsyncContext#run. Please make sure that the appropriate middleware/interceptor for your environment is executed.`
        );

        // Set the prototype explicitly.
        Object.setPrototypeOf(this, TracingNotInitializedException.prototype);
    }
}

**Comment by apricote** [comment]
Solved by #154
