### ISSUE TITLE
update to nest to version 8?

### ISSUE THREAD

**Issue by schealex** [narando/nest-xray#310]
Hey there,

i would really love to use this, any plans for updating it to work with nest 8?

Regards
Alex

**Comment by MarcMogdanz** [comment]
Hey!

There are no plans directly, but I'll look try to look into it in the near future, but feel free to create a PR yourself, even if it's not fully working! :)

**Comment by schealex** [comment]
Hi @MarcMogdanz i am not able to do that because the dependency of "@narando/nest-axios-interceptor" also requieres nest < 8 and there is no source for that package.

**Comment by MarcMogdanz** [comment]
Yea, basically the same situation over there. Can't guarantee anything but I'll talk with @apricote about it and I guess we'll look into it when we find the time. :)

**Comment by schealex** [comment]
nvm. found the source. Upgraded to v8 in both and fixed the issues.
Tests run fine but there's probably gonna be problems with backward compatibility because I also replaced the obsolete HttpModule.

**Comment by apricote** [comment]
This was released as `v2.0.0`.
